# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user_categories',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
