# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-11 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='events_tags',
            field=models.ManyToManyField(related_name='tags', to='events.Event'),
        ),
    ]
