# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180311_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/Categories'),
        ),
        migrations.AlterField(
            model_name='category',
            name='events_categories',
            field=models.ManyToManyField(related_name='categories', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user_categories',
            field=models.ManyToManyField(related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
