# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180121_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='city_hall',
        ),
    ]
