# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-01 19:35
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='none/icon_user.jpg', upload_to=accounts.models.get_image_filename),
        ),
    ]
